# Generated by Django 5.1.6 on 2025-04-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciodeportivo',
            name='tipo_espacio',
            field=models.CharField(choices=[('cancha', 'Cancha'), ('gimnasio', 'Gimnasio'), ('piscina', 'Piscina'), ('mesa', 'Mesa'), ('otro', 'Otro')], max_length=20),
        ),
    ]
